### ISSUE TITLE
pst-parser not getting messages enteries 

### ISSUE THREAD

**Issue by Anil890-bt** [IJMacD/pst-parser#1]
only root folders are displaying not parsing message or subfolder data can you help for this  not parsing content data like message enteries fix this bug
![Screenshot 2024-02-14 152316](https://github.com/IJMacD/pst-parser/assets/134353605/f2a05499-0abc-48bd-94e7-db7e317d4c15)

**Comment by Anil890-bt** [comment]
@IJMacD

**Comment by IJMacD** [comment]
Hi Anil,

you need to recursively call `getSubFolderEntries()` for each level.


    // Get listing of subfolders
    const entries = rootFolder.getSubFolderEntries();

    // Get folder object for the first subfolder
    const subFolder = rootFolder.getSubFolder(entries[0].nid);

    console.log(subFolder.displayName);

    const subEntries = subFolder.getSubFolderEntries();

    for (const subEntry of subEntries) {
        const subSubFolder = subFolder.getSubFolder(subEntry);

        console.log(subSubFolder.displayName);

        // Get first 5 message entries
        const messageEntries = subSubFolder.getContents(0, 5);

        // Get actual message object
        const message = subSubFolder.getMessage(messageEntries[0].nid);

        console.log(message);
    }
    
See the source for this [demo project](https://ijmacd.github.io/pst-browser/) for how to get data at multiple levels.
e.g. Take a look at https://github.com/IJMacD/pst-browser/blob/master/src/components/ContentsViewPage.js and https://github.com/IJMacD/pst-browser/blob/master/src/components/FolderTree.js

**Comment by Anil890-bt** [comment]
@IJMacD  Thanks for solution

**Comment by Anil890-bt** [comment]
@IJMacD can i read Ost files also with this pst browser @IJMacD

**Comment by IJMacD** [comment]
It seems it might be possible, but I've never tried.

According to [Wikipedia](https://en.wikipedia.org/wiki/Personal_Storage_Table) the two files share a common specification so it's possible that my parser might be able to read some parts of `.ost` files as well. If you have any success let me know how you get on.

**Comment by Anil890-bt** [comment]
@IJMacD when a upload ost then showing this not a Btreepage  
![Screenshot 2024-02-26 171152](https://github.com/IJMacD/pst-parser/assets/134353605/47d6495e-c99f-4026-9331-023afb0310e7)
@IJMacD check it can you help me for this

**Comment by IJMacD** [comment]
If you send me an `ost` file, I might be able to have a look over the next few days.

**Comment by Anil890-bt** [comment]
Sure, here you go!
 ***@***.*** - tt.ost

**Comment by Anil890-bt** [comment]
hey you received the file ??

**Comment by IJMacD** [comment]
Yes, I received the file thanks.

I'll try to find some time to look at it.

**Comment by Anil890-bt** [comment]
Great.

**Comment by Anil890-bt** [comment]
@IJMacD   you get the solution ?

**Comment by IJMacD** [comment]
I managed to find time to look into it, but wasn't able to get it working fully. 

I get the impression in general OST files are virtually identical to PST files but the one you sent me was actually a OST 2013 version file which uses larger block sizes for the BTree pages. (4096 bytes vs. 512 bytes)

(See: https://blog.mythicsoft.com/ost-2013-file-format-the-missing-documentation/ for more details)

It would take a little bit of work to adjust all the offsets and it might be something I do in the future.
In the meantime however, I found this excellent site which is another pure JS implementation and might serve your purposes. 

https://goldfynch.com/pst-viewer/

**Comment by Anil890-bt** [comment]
@IJMacD hey ijmacD any update about ost support in pst-parser

**Comment by Anil890-bt** [comment]
@IJMacD hey ijmacD any update about ost support in pst-parser

**Comment by IJMacD** [comment]
No, no update. I'm not currently working on it.

At the time of my last message I added support for opening OST files in general (if they follow the PST spec), but haven't added support for OST 2013 files, which have larger page sizes. If you implement it yourself please send a pull request and I'll consider including it in the library. You can see the work I started in the most recent two commits on the master branch.

In the meantime I really do suggest trying out that other site - their implementation seems pretty solid.

**Comment by Anil890-bt** [comment]
ok sure

**Comment by Anil890-bt** [comment]
hey @IJMacD  I hope this message finds you well. I am reaching out regarding the pst-parser library, which I have been using to work with PST files. However, I noticed that the library is unable to parse OST files due to differences in their structure.

I understand that OST files have a distinct format, even though they share some similarities with PST files. Could you kindly provide guidance or recommendations on handling OST files with pst-parser? Alternatively, if pst-parser is not designed for OST files, I would appreciate any suggestions for adapting the library or leveraging additional tools/libraries for this purpose.

**Comment by Anil890-bt** [comment]
https://learn.microsoft.com/en-us/office/client-developer/outlook/mapi/ipm-subtree
